PollSurveySystem/Models/ViewModels/AddPollViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PollSurveySystem.Models.ViewModels
{
    public class AddPollViewModel
    {
        [Required(ErrorMessage = "Question is required.")]
        public string Question { get; set; }
        [Required(ErrorMessage = "Answer is required.")]
        public string Answer { get; set; }
    }
}

PollSurveySystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PollSurveySystem.Models;
using PollSurveySystem.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PollSurveySystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPollManager _pollManager;

        public HomeController(IPollManager pollManager)
        {
            _pollManager = pollManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ViewCurrentPoll(int Id)
        {
            return View(_pollManager.ViewCurrentPoll(Id));
        }

        [HttpGet]
        public IActionResult GetActivePolls()
        {
            IEnumerable<AllPollsViewModel> polls = _pollManager.GetActivePolls();
            return View(polls.ToList());
        }

        public IActionResult AddPoll()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPoll(AddPollViewModel poll)
        {
            if (ModelState.IsValid)
            {
                if (_pollManager.AddPoll(poll))
                { ViewBag.Message = "Poll added successfully!"; }
                else return NotFound();
            }
            ModelState.Clear();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PollSurveySystem/Controllers/PollsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PollSurveySystem.Models;
using PollSurveySystem.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PollSurveySystem.Controllers
{
    public class PollsController : Controller
    {
        private readonly IPollManager _pollManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public PollsController(IPollManager pollManager, IHttpContextAccessor httpContextAccessor)
        {
            _pollManager = pollManager;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SubmitVote(int PollID, int PollOption)
        {
            string cookieKey = "hasVoted" + PollID;
            string cookieValue = _httpContextAccessor.HttpContext.Request.Cookies[cookieKey];
            if (PollOption==0)
            {
                return View(_pollManager.ViewCurrentPoll(PollID));
            }
            else
            {
                if (cookieValue != null)
                {
                    if (cookieValue.Equals("has voted for" + PollID))
                    {
                        { ViewBag.Message = "You have already voted"; }
                        return View(_pollManager.ViewCurrentPoll(PollID));
                    }
                }
                _pollManager.SubmitVote(PollID, PollOption);
                return View(_pollManager.ViewCurrentPoll(PollID));
            }          
        }
    }
}

PollSurveySystem/Views/Home/AddPoll.cshtml
@{
    ViewData["Title"] = "Add Poll";
}

@model PollSurveySystem.Models.ViewModels.AddPollViewModel

<div class="add-poll-flex-container">
    @if (ViewBag.message != null)
    {
        <div class="alert alert-primary" role="alert">
            @ViewBag.message
        </div>
    }
    <h1>Add Poll</h1>

    <form asp-controller="Home" asp-action="AddPoll" method="post">
        <div class="form-group">
            <label asp-for="Question">Question:</label>
            <input asp-for="Question" class="form-control" value="" required>
        </div>
        <div class="form-group">
            <label asp-for="Answer">Answers:</label>
            <textarea asp-for="Answer" class="form-control" placeholder="" required></textarea>
            <div class="alert alert-light d-flex align-items-center" role="alert">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" 
                     class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
                <div>
                    Please write each answer on a new line.
                </div>
            </div>
        </div>
        <button asp-controller="Home" asp-action="AddPoll" class="btn btn-light btn-lg">Submit</button>
    </form>
</div>

PollSurveySystem/Views/Home/GetActivePolls.cshtml
@{
    ViewData["Title"] = "Active Polls";
}

@model IEnumerable<PollSurveySystem.Models.ViewModels.AllPollsViewModel>


<div class="polls-grid-container">
    @foreach (var item in Model)
    {
        <div class="card" style="min-height: 13rem;">
            <div class="card-body">
                <h5 class="card-title">@item.PollID. @item.Question</h5>
                <div class="get-started-button">
                    <button class="btn btn-light btn-lg">@Html.ActionLink("Vote", "ViewCurrentPoll", new { id = item.PollID }) </button>
                </div>
            </div>
        </div>
    }
</div>

PollSurveySystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="index-page-text">
    <div class="text-center">
        <h1 class="display-4">Welcome to the world's largest poll survey system!</h1>
        <p>
            There is a question that really bothers you?<br />
            You want to show your friend that you're right and they're wrong?<br />
            Ask our worldwide community of poll takers and receive honest opinion on various topics!
        </p>
    </div>
</div>
<div class="get-started-button">
    <button class="btn btn-outline-dark btn-lg">@Html.ActionLink("Get Started", "GetActivePolls")</button>
</div>
<div class="week-quote">
    <div class="card">
        <div class="card-header">
            Quote of the Week
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>
                    A telephone survey says that 51 percent of college students drink until they pass out at least once a month.
                    The other 49 percent didn't answer the phone.
                </p>
                <footer class="blockquote-footer">Craig Kilborn in <cite title="https://www.azquotes.com/">www.azquotes.com</cite></footer>
            </blockquote>
        </div>
    </div>
</div>

PollSurveySystem/Views/Home/ViewCurrentPoll.cshtml
@{
    ViewData["Title"] = Model.Question;
}

@model PollSurveySystem.Models.ViewModels.PollDetailsViewModel


<div class="single-poll-card">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">@Model.PollID. @Model.Question</h5>
            <form asp-controller="Polls" asp-action="SubmitVote" method="get">
                <input asp-for="PollID" class="form-check-input" value="@Model.PollID" type="hidden">
                @foreach (var o in Model.PollOption)
                {
                    <div class="form-group form-check">
                        <input asp-for="PollOption" class="form-check-input" type="radio" value="@o.PollOptionID">
                        <label class="form-check-label" asp-for="PollOption">
                            @o.OptionValue
                        </label>
                    </div>
                }
            <div class="poll-control-button">
                <button asp-controller="Polls" asp-action="SubmitVote" class="btn btn-light">Vote</button>
                <button asp-controller="Polls" asp-action="SubmitVote" class="btn btn-light">View Results</button>
            </div>
            </form>
            @*<div class="view-results-button">
            <button class="btn btn-light btn-lg">@Html.ActionLink("View Results", "SubmitVote", "Polls", new { PollID = Model.PollID }) </button>
            </div>*@
        </div>
    </div>
</div>